### ISSUE TITLE
When installing gvmd, get a /run/gvmd Permission Denied

### ISSUE THREAD

**Issue by romelBen** [Jarthianur/gvm-install-script#13]
Back at it again with the permissions issue again. Trying to figure on my side and probably on your side too?

```
--Installing /opt/gvm/var/lib/gvm/gvmd
-- Installing /run/gvmd
CMake Error at cmake_install.cmake directory "/run/gvmd": Permission denied.
make: *** [Makefile:119: install] Error 1
```

**Comment by Jarthianur** [comment]
I'll have a look into it.

**Comment by Jarthianur** [comment]
Ok they issue is, that they again changed the pathing, so it requires to have the socket in /run/gvmd/. My setup ran from /run/gvm/ fine. Maybe this is a local thing, I'll try to find a proper way to handle this. BUT, greenbone also split gsad from gsa, and did some minor changes like branching schema on openvas-smb too. I'll have to figure out how to build this whole thing again.

By the way, how do you think about a move to ansible?

**Comment by romelBen** [comment]
PATHing has been a big proponent of them which is getting annoying. And to answer your question, Ansible is great. It would be great if we can have a bash script with and Ansible being used to install GVM.

**Comment by Jarthianur** [comment]
I think, I've sorted it out. Could you review the changes in #14 to be working for you?
There is one leftover that might cause issues in the future. The install of gvm-libs requires the /run/gvm directory to be present, but there is apparently no runtime needing this thing. I'm not sure, whether it's actually used somewhere, but if so we will have to put an entry into the tempfiles config to assure the directory to exist upon reboot.

**Comment by romelBen** [comment]
Will check this out tomorrow!

**Comment by romelBen** [comment]
So as for the systemd `gvmd.service`, it is not working. It times out trying to get itself built. Will have to dig into "why" it is posing that error.

**Comment by Jarthianur** [comment]
Could you briefly describe what changes you did apply to the script, and what the error looks like?

**Comment by romelBen** [comment]
Sorry it took some time, here is the error for the `gvmd.service`. I ran `journalctl -xe` to grab the error message:
```
Dec 04 22:59:56 ip-172-31-60-47 sudo[29907]:     root : TTY=unknown ; PWD=/home/ubuntu ; USER=root ; ENV=GVM_INSTALL_PREFIX=/opt/gvm ; COMMAND=/usr/bin/bash -c create_gvmd_service () 
                                             { 
                                                 set -e;
                                                 cat <<EOF > /etc/systemd/system/gvmd.service
                                             [Unit]
                                             Description=Open Vulnerability Assessment System Manager Daemon
                                             Documentation=man:gvmd(8) https://www.greenbone.net
                                             Wants=postgresql.service ospd-openvas.service
                                             After=postgresql.service ospd-openvas.service network.target networking.service
                                             [Service]
                                             Type=forking
                                             User=gvm
                                             Group=gvm
                                             PIDFile=/run/gvmd/gvmd.pid
                                             RuntimeDirectory=gvmd
                                             RuntimeDirectoryMode=2775
                                             EnvironmentFile=$GVM_INSTALL_PREFIX/etc/default/gvmd
                                             ExecStart=$GVM_INSTALL_PREFIX/sbin/gvmd --osp-vt-update=/run/ospd/ospd-openvas.sock -c /run/gvmd/gvmd.sock --listen-group=gvm
                                             Restart=always
                                             TimeoutStopSec=10
                                             PrivateTmp=true
                                             [Install]
                                             WantedBy=multi-user.target
                                             EOF
                                             
                                                 systemctl daemon-reload;
                                                 systemctl enable --now gvmd.service;
                                                 systemctl --no-pager status gvmd.service
                                             };
Dec 04 22:59:56 ip-172-31-60-47 sudo[29907]:     root : (command continued) create_gvmd_service
Dec 04 22:59:56 ip-172-31-60-47 sudo[29907]: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 04 22:59:56 ip-172-31-60-47 systemd[1]: Reloading.
Dec 04 22:59:57 ip-172-31-60-47 systemd[1]: Reloading.
Dec 04 22:59:57 ip-172-31-60-47 systemd[1]: gvmd.service: Failed to load environment files: No such file or directory
Dec 04 22:59:57 ip-172-31-60-47 systemd[1]: gvmd.service: Failed to run 'start' task: No such file or directory
Dec 04 22:59:57 ip-172-31-60-47 systemd[1]: gvmd.service: Failed with result 'resources'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
```

**Comment by romelBen** [comment]
My installation of `gvmd` and the `gvmd.service` are located here in my code: https://github.com/romelBen/gvm_bash_script

**Comment by Jarthianur** [comment]
The issue seems to be this one: `EnvironmentFile=$GVM_INSTALL_PREFIX/etc/default/gvmd`
If this file does not exist, the service fails - I get the very same error like you.
The environment file is not created directly from my script. I need to find out, where this thing comes from - probably from `make`ing gvmd.

**Comment by Jarthianur** [comment]
Works on my machine.
