### ISSUE TITLE
ospd-openvas installation fails on 20.08

### ISSUE THREAD

**Issue by 0d4y5** [Jarthianur/gvm-install-script#2]
First of all congratulations for the script! Really great work trying to automate this task.

I am trying to use your script to deploy a GVM20.08. As you said that the script is work in progress, has this ever worked for you?
For me it breaks at the ospd-openvas part, and I did changed Python version from 3.7 of the script to 3.8

```
[INFO ] 12:03:34 install.sh->main:: Install ospd-openvas
environment: line 8: /var/opt/gvm/bin/ospd-scanner/bin/activate: No such file or directory
[ERROR] 12:03:34 install.sh->exec_as:: Installation failed!
```

**Comment by Jarthianur** [comment]
Thanks for being interested in this!

Yes the script worked for me, at least at the point of committing.
I know about that failure already, as well as some other little issues.
Sadly I didn't had the time to look into it yet, but will do in the next days asap.

If you need a solution on this right now, you may try to run that part manually line by line to identify what's actually failing.
I'm pretty sure it's just some minor thing in the end.
Feel free to provide your findings here then.

Btw, I would recommend to comment out the feed sync at the end for testing purposes.

**Comment by 0d4y5** [comment]
I had a chance to look into this and apparently the issue lies with this line here:
```
if [ $(ps aux | grep ospd-scanner | wc -l) -eq 1 ]; then
        virtualenv --python python3.7 "$GVM_INSTALL_PREFIX/bin/ospd-scanner/"
```

It seems that the virtualenv command does not run, I tried this also on different distros and the behavior remains the same. 
If I run `ps aux | grep ospd-scanner | wc -l` it does come back with result 1, so I don't know why it does not run properly.
If I run `virtualenv --python python3.7 "/var/opt/gvm/bin/ospd-scanner/"` and then re-launch the script, it works. 
However it seems to build a broken scanner, as there are 3 errors:

1. `Failed to find port_list '33d0cd82-57c6-11e1-8ed1-406186ea4fc5'`
which is related to missing Configuration > Ports Lists

2. `Failed to find report format 'a994b278-1f62-11e1-96ac-406186ea4fc5'`
which appears when browsing to the Scans > Reports page

3. Failed to find config 'daba56c8-73ec-11df-a475-002264764cea'
which is generated when creating a new scan and after I have created a new port list to try to fix the 1st error.

I have tried both on Ubuntu 20.04 and on Debian 10.7 and the behavior is exactly the same.

Following this guide, I can get a server running, but obviously is manual work and seems to be based on the very same guide that you referenced to create the script.:
https://pentestit.de/gvm-20-08-auf-ubuntu-server-20-04-installieren/

**Comment by Jarthianur** [comment]
Thanks for your work on this.
I'm right at the moment setting up a clean debian test VM to tackle this.
Will keep you updated.

**Comment by Jarthianur** [comment]
Branch `fix_issue_2` contains a fix for the virtualenv thing.
Please don't ask me why I checked for the process instead of the directory...

Will take a look into the other errors now.

**Comment by 0d4y5** [comment]
Thanks for taking a look at this and for fixing the virtualenv thing. 
The errors are in the WebUI, and they persists even checking after 24 hours, so it definitely left more than enough time for the feeds and port lists etc. to be parsed :) I have just confirmed that still there is no port list.
Can you give me the hash of the image you used, just to give it another try? Unless you used this:
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.7.0-amd64-netinst.iso
SHA256: B317D87B0A3D5B568F48A92DCABFC4BC51FE58D9F67CA13B013F1B8329D1306D
Yes I am aware of the disconnections (and great work with the retries!) but for example during my installation of debian there was none. All ran smoothly aside from the virtualenv that I ran manually and then re-launched the script.
I was wondering if you are willing to give it a try in Ubuntu 20.04? 
I am wondering if this could have actually been caused by something not having been downloaded properly.

I am also going to upload few screenshot so that you also see what I see :)

![image](https://user-images.githubusercontent.com/70801239/101886828-5449ed00-3b9c-11eb-960d-262a7222507f.png)

![image](https://user-images.githubusercontent.com/70801239/101887257-e5b95f00-3b9c-11eb-9625-a04a8fb8a13a.png)

![image](https://user-images.githubusercontent.com/70801239/101887166-c4f10980-3b9c-11eb-882f-8b4c9a67dc72.png)

![image](https://user-images.githubusercontent.com/70801239/101887631-709a5980-3b9d-11eb-930c-0555864b266c.png)

![image](https://user-images.githubusercontent.com/70801239/101887862-b3f4c800-3b9d-11eb-962a-b4a9921491d1.png)

![image](https://user-images.githubusercontent.com/70801239/101889753-13ec6e00-3ba0-11eb-807b-a3b621b4b6cc.png)

**Comment by Jarthianur** [comment]
Thanks for also providing screenshots.

Just to add some more transparency, following is my testing setup and procedure:

- using current debian-10.7.0-amd64-netinst.iso
- installed in a VM on virtualbox & some pkgs like vim, htop, sudo (do snapshot)
- cloning this repo to /opt and checkout branch to test (do snapshot)
- export GVM_VERSION=20.08 and run script as root
- wait until finished (do snapshot)
- visit VM at port 443 and look at Administration->Feed Status

For debugging purposes I've manipulated the script to stop after deb installs to make another snapshot, where I can revert to.
I also commented all feed syncs out to only fetch the GVMD_DATA feed as it is the one responsible for port lists etc.

What I could notice in the last run, was that when I interrupted the install script (unmodified), then for some reason the feeds are inconsistent and dont get imported properly; rerunning does not help then! Only deleting the xml's under /var/opt/gvm/var/lib/gvm and refetching the feeds did lead to success.
A full run from a clean snapshot was successfully though.

What might happen is that the gvmd imports the metadata and then is not able to handle inconsistent data on disk or whatever.
So I would suggest, you revert your debian setup (I really recommend VM snapshots) to a clean state, or delete the whole /var/opt/gvm directory and user. Then please check, that you have enough space on disk (just in case, I could bet you have already).
Then run the script again on the clean setup.
These issues about metadata being imported, but actual data not could also be caused by failed downloads.
I had it once, that my IP address was blocked for a few minutes - to much testing :D

Although I don't like ubuntu that much, I'll give it a try. It's probably working without much modification.
Centos could be also interesting...

**Comment by Jarthianur** [comment]
I've did another test run on debian which went fine.
Apart from that, I've tested the script on an ubuntu 20.04 VM. Only a single little change was required to get it working, as seen in #3 .

Could you please test it again from a clean setup and verify it's working for you?

**Comment by 0d4y5** [comment]
Thanks again for making some other improvements.

First of all I want to tell you that the installation on Debian that seemed not to be successful in my earlier tests, actually it is successful. I did not touch it for a couple of weeks and I noticed today that the Port Lists have been populated and it is able to scan. So it may be that feeds just take an incredibly long time to get parsed. In my experience, in the worst case scenario it could take few hours, not weeks.

Question: how long do you wait from the moment that your script ends to the moment that you go to the GUI and check if the installation was successful? Also, what are your specs? I use 2 cpu, 4gb of memory and 50gb hard drive - so yes I have free space :)
In regards to the Ubuntu installation, I did run the script on a fresh install.
What I noticed is that it updates the NVT, then it fails but without giving errors. Below an example:


```
[INFO ] 12:37:50 install.sh->main:: Update SCAP data
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 43 bytes  received 113 bytes  312.00 bytes/sec
total size is 13  speedup is 0.08
[INFO ] 12:38:05 install.sh->main:: Update CERT data
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 43 bytes  received 114 bytes  314.00 bytes/sec
total size is 13  speedup is 0.08
[INFO ] 12:38:20 install.sh->main:: Sync feeds
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 43 bytes  received 114 bytes  314.00 bytes/sec
total size is 13  speedup is 0.08
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 43 bytes  received 113 bytes  312.00 bytes/sec
total size is 13  speedup is 0.08
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 43 bytes  received 114 bytes  314.00 bytes/sec
total size is 13  speedup is 0.08
[INFO ] 12:38:36 install.sh->main:: Create weekly feed update service
[INFO ] 12:38:37 install.sh->main:: GVM installation completed
[WARN ] 12:38:37 install.sh->main:: It might still take some time for the plugin feed to be imported!



```
____________


If I try to run it several other times of course it will work, but it looks like I have to wait 5 minutes or more to make this working.


```

[INFO ] 12:46:40 install.sh->main:: Update SCAP data
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 43 bytes  received 113 bytes  312.00 bytes/sec
total size is 13  speedup is 0.08
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
./
COPYING
          1,719 100%    1.64MB/s    0:00:00 (xfr#1, to-chk=43/45)
nvdcve-2.0-2002.xml
     15,354,093 100%  400.25kB/s    0:00:37 (xfr#2, to-chk=42/45)
nvdcve-2.0-2003.xml
      4,332,608 100%  381.28kB/s    0:00:11 (xfr#3, to-chk=41/45)
nvdcve-2.0-2004.xml
      8,910,182 100%  397.45kB/s    0:00:21 (xfr#4, to-chk=40/45)
nvdcve-2.0-2005.xml
     14,615,135 100%  394.03kB/s    0:00:36 (xfr#5, to-chk=39/45)
nvdcve-2.0-2006.xml
     23,948,726 100%  394.37kB/s    0:00:59 (xfr#6, to-chk=38/45)
```
	 
	 

I am not running your script as root as the original instructions indicate to run the commands from a standard account. I don't think this is going to play any role, but I just mention it for the sake of transparancy.

I saw that you edited the sleep time from 5 to 10 seconds between NVT, SCAP and CERT data. What do you think about making it 400, maybe with a mention that the process is sleeping for 400 seconds, with the timestamp on the same line? It is an installation that goes on for few hours, so if I wait 20 minutes more it does not really bother me if in the end it works, without having to manually run the script an indefinite amount of time.

**Comment by Jarthianur** [comment]
Ok first about the ubuntu issue.
Log lines like
```
receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)
```
are exactly what you see, if you are attempting "too many" sync requests in a short time.
Well I think the only way would be to increase the wait timeout even more, but 2 minutes should be enough.
It is pretty hard to catch that as the request itself is "successful".

Usually when I run a test, I visit the web page immediately, just to confirm the feed status is "updating...".
Although the gvmd data (port lists etc.) stuff should be updated pretty fast as its not that much of data.
Nevertheless should the whole process not take days, but a few hours at most.
But this may also depend on general IO performance, as there are components like redis and postgres involved.
I remember installing the whole thing in a kali VM on laptop via the builtin scripts also took 4-6 hours or so.

My test VM runs under virtualbox with 2 vCPUs, 4GB RAM and 16GB disk space.
The actual CPU is an athlon 3000g and the vdi disk file is placed on a nvme SSD.
So CPU power should not be a bottleneck here ;) , but disk IO might have a larger impact.
I can imagine when you run this thing on a good old HDD it might take significantly longer as on a modern nvme.

And yes, it should not be required to run the script as root. Every step that requires higher privileges asks for *sudo* permissions. So this should not be an issue.

**Comment by 0d4y5** [comment]
So... I logged in first thing in the morning to see if overnight the feeds were parsed or something: nothing, no port lists and errors as in the previous screenshots.
Then I thought that it could not be that it takes weeks to fix itself parsing stuff, and I realized that it might have been the cron job that runs the gvm-update-feed.sh script. I logged in as the gvm user and ran the gvm-update-feed.sh script... it fixed the scanner! Port lists were parsed and I was able to run a scan on the spot. 

I am now going to try a fresh install, and then run the gvm-update-feed.sh script straight away and see what happens, if it works it could be the conclusive task, otherwise I would be curious to see how gvm behaves if sleep between feeds update are implemented.

**Comment by 0d4y5** [comment]
It works! I applied the 400 seconds timeout directly, as I thought that running the gvm-update-feed.sh means that I would still need to manually run the script an undetermined amount of times. I did not applied the change to the update_nvt() function as is the first that runs. I was able to login and run a scan straight away, with no errors of any kind!

This is the very simple tweak I did to your code:

```
function update_certdata() {
    echo "Sleeping for 400 seconds to avoid Greenbone Servers ban..."
    sleep 400
    set -e
    . /etc/profile.d/gvm.sh
    greenbone-certdata-sync
}

function update_scapdata() {
    echo "Sleeping for 400 seconds to avoid Greenbone Servers ban..."
    sleep 400
    set -e
    . /etc/profile.d/gvm.sh
    greenbone-scapdata-sync
}

function sync_feed() {
    echo "Sleeping for 400 seconds to avoid Greenbone Servers ban..."
    sleep 400
    set -e
    . /etc/profile.d/gvm.sh
    greenbone-feed-sync --type "$FEED_TYPE"
}
```

Actually I noticed that cert data did not ran in the first place:

```
[INFO ] 14:39:44 install.sh->main:: Update CERT data
[sudo] password for user:
Sleeping for 400 seconds to avoid Greenbone Servers ban...
Greenbone community feed server - http://feed.community.greenbone.net/
This service is hosted by Greenbone Networks - http://www.greenbone.net/

All transactions are logged.

If you have any questions, please use the Greenbone community portal.
See https://community.greenbone.net for details.

By using this service you agree to our terms and conditions.

Only one sync per time, otherwise the source ip will be temporarily blocked.

receiving incremental file list
timestamp
             13 100%   12.70kB/s    0:00:00 (xfr#1, to-chk=0/1)

sent 43 bytes  received 113 bytes  312.00 bytes/sec
total size is 13  speedup is 0.08

```
However, as the sync_feed() function essentially recalls each of them including the 400 seconds delay, it ran just fine.

The only outstanding thing is that I am asked again the sudo password after some time, but if you said that the script works anyway when it is ran from root, that might fix that too. Example:

```
[INFO ] 14:39:44 install.sh->main:: Update CERT data
[sudo] password for user:
Sleeping for 400 seconds to avoid Greenbone Servers ban...
```

I will give it another try over the next couple of days just to make sure it was not just a lucky strike, but I do think that all the errors/issues were caused by the feeds that were not downloaded properly.

**Comment by 0d4y5** [comment]
I just wanted to confirm that with the added delay as I mentioned in my previous comment, it works fine on Ubuntu 20.08
I am closing the issue as I am sorted for now. 
Thanks for your help in fixing the other things!

**Comment by Jarthianur** [comment]
I'm happy that we got this resolved.
Thanks for your patience and effort testing this.

Just for the reference, I've reordered the install steps so initial sync is done at last.
Now one does not have to rerun the script and may just start the update service.
I've also added the sleeps to the update service, and increased the timeouts to 5 minutes.
