### ISSUE TITLE
problem during authentication

### ISSUE THREAD

**Issue by PatriceBLD** [Jarthianur/gvm-install-script#8]
Hello, 
After installing the script, when I restart I get this message: "An error occured during making the request. Most Likely the web does not responding" when I try to authenticate myself with the admin login and the password: admin

Can you help me ?

**Comment by Jarthianur** [comment]
Hi @PatriceBLD,
I've faced exactly the same behavior today.
Somehow the socket path of gvmd has changed, or could not be created, starting with some recent commit.
I have already adjusted the script, so please pull and build it again.
